//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makabaka {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Makabaka.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 API response data is null: {0}. 的本地化字符串。
        /// </summary>
        internal static string APIResponseDataNull {
            get {
                return ResourceManager.GetString("APIResponseDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API response does not indicate success: [{0}] {1} ({2}). 的本地化字符串。
        /// </summary>
        internal static string APIResponseError {
            get {
                return ResourceManager.GetString("APIResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API timeout: {0}. 的本地化字符串。
        /// </summary>
        internal static string APITimeout {
            get {
                return ResourceManager.GetString("APITimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bot task was canceled. 的本地化字符串。
        /// </summary>
        internal static string BotTaskCanceled {
            get {
                return ResourceManager.GetString("BotTaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to configure network service. Please check &quot;appsettings.json&quot;. 的本地化字符串。
        /// </summary>
        internal static string ConfigureNetworkServiceFailed {
            get {
                return ResourceManager.GetString("ConfigureNetworkServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] API send task canceled. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketAPISendTaskCanceled {
            get {
                return ResourceManager.GetString("ForwardWebSocketAPISendTaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Connect failed. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketConnectFailed {
            get {
                return ResourceManager.GetString("ForwardWebSocketConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Connecting to {0}. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketConnecting {
            get {
                return ResourceManager.GetString("ForwardWebSocketConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Connect suceess. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketConnectSuccess {
            get {
                return ResourceManager.GetString("ForwardWebSocketConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Disconnected. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketDisconnected {
            get {
                return ResourceManager.GetString("ForwardWebSocketDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Error while processing data. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketProcessError {
            get {
                return ResourceManager.GetString("ForwardWebSocketProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Received: {0} 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketReceived {
            get {
                return ResourceManager.GetString("ForwardWebSocketReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Send packet failed. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketSendFailed {
            get {
                return ResourceManager.GetString("ForwardWebSocketSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Sent: {0} 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketSent {
            get {
                return ResourceManager.GetString("ForwardWebSocketSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ForwardWebSocket] Task canceled. 的本地化字符串。
        /// </summary>
        internal static string ForwardWebSocketTaskCanceled {
            get {
                return ResourceManager.GetString("ForwardWebSocketTaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] {1}: {2} 的本地化字符串。
        /// </summary>
        internal static string GroupMessage {
            get {
                return ResourceManager.GetString("GroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to deserialize message as {0}. 的本地化字符串。
        /// </summary>
        internal static string MessageDeserializeAsFailed {
            get {
                return ResourceManager.GetString("MessageDeserializeAsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to deserialize message. 的本地化字符串。
        /// </summary>
        internal static string MessageDeserializeFailed {
            get {
                return ResourceManager.GetString("MessageDeserializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while handling message. 的本地化字符串。
        /// </summary>
        internal static string MessageHandleError {
            get {
                return ResourceManager.GetString("MessageHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to process message. 的本地化字符串。
        /// </summary>
        internal static string MessageProcessedFailed {
            get {
                return ResourceManager.GetString("MessageProcessedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string PrivateMessage {
            get {
                return ResourceManager.GetString("PrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting bot... 的本地化字符串。
        /// </summary>
        internal static string StartingBot {
            get {
                return ResourceManager.GetString("StartingBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping bot... 的本地化字符串。
        /// </summary>
        internal static string StoppingBot {
            get {
                return ResourceManager.GetString("StoppingBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected exception. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown API echo: {0}. 的本地化字符串。
        /// </summary>
        internal static string UnknownAPIEcho {
            get {
                return ResourceManager.GetString("UnknownAPIEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported segment type &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedSegmentType {
            get {
                return ResourceManager.GetString("UnsupportedSegmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register web socket processor: [{0}] {1}. 的本地化字符串。
        /// </summary>
        internal static string WebSocketProcessorRegister {
            get {
                return ResourceManager.GetString("WebSocketProcessorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while registering web socket processor for method {0}. 的本地化字符串。
        /// </summary>
        internal static string WebSocketProcessorRegisterError {
            get {
                return ResourceManager.GetString("WebSocketProcessorRegisterError", resourceCulture);
            }
        }
    }
}
